### ISSUE TITLE
Getting "Please compile /data/config.yml file" in logs

### ISSUE THREAD

**Issue by robson90** [bonny1992/sonarr-radarr-notification-aggregator#1]
As described in the title I get 

`Please compile /data/config.yml file`

In my Logs.

Docker Configuration:
notification-aggregator:
      image: bonny1992/sonarr-radarr-notification-aggregator:latest
      container_name: notification-aggregator
      networks:
          web:
              ipv4_address: 172.19.0.18
      environment:
        - TZ=${TZ}
        - PUID=${USER_UID}
        - PGID=${USER_GID}
      volumes:
        - /volume1/docker/notification-aggregator:/data
      ports:
        - "5445:5445"

My Config yaml:
custom_movie_entry: '{TITLE} ({YEAR}) | {QUALITY} | {IMDB_LINK} alle {TIME}'
custom_quiet_mode_message: "\U0001F4A4 *Modalit\xE0 notte* \U0001F4A4"
custom_too_long_message: 'Troppi caratteri.\nN. episodi Serie TV importati: {N_TV}\nN.
  film importati: {N_MOVIE}'
custom_tv_entry: '{SERIES} - {SEASON}x{EPISODE} - {TITLE} | {QUALITY} alle {TIME}'
discord_webhook: 'https://discordapp.com/api/webhooks/WEBHOOKID'
domain: 'notification-aggregator.my.domain.com'
end_quiet: 9
safe_key: YML6xHdRESTOFKEYLOXbQRC02vPEMSlUBlx2HtnqHrMTfdwrAZCfgEPKG0WBAwwai
skip_hours: 1
start_quiet: 21
telegram_bot_token: null
telegram_chat_id: null
timezone: Europe/Berlin

My Logs from the Container. PUID and PGID is XXX for security reasons:
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 10-adduser: executing... 

-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \ 
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/

Brought to you by linuxserver.io
-------------------------------------

To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------

User uid:    XXX
User gid:    XXX
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Please compile /data/config.yml file
Mon Sep  7 12:00:24 2020	| NOTIFICATOR   |		Starting the notificator...
Please compile /data/config.yml file
Please compile /data/config.yml file

Additional question: When I go to the domain. What should I see ? Feel free contact me for any additional information.

**Comment by bonny1992** [comment]
Yeah... I may have yet to implement something to disable the Telegram part, as for now only Discord is not mandatory to have.

I'll fix it right now.

About the domain: Usually, nothing, as the url `domain.com/safekey/sonarr` or `radarr `act only as a receiving webhook. It's not visual like Sonarr and Radarr.

**Comment by robson90** [comment]
Okay, thank u very much ! I would fix it myself, but I suck at python. Im sorry ;)

**Comment by bonny1992** [comment]
You have nothing to be sorry, @robson90 ! I should have implemented it in the first place.

Also I should have fixed it by now, please delete the container, the image and the config.yml file.

If you're not familiar:
```
docker rm -f notification-aggregator
docker rmi bonny1992/sonarr-radarr-notification-aggregator:latest
rm -rf /volume1/docker/notification-aggregator/config.yml
```

You should recompile the file after creation, I have added a couple of keys named `enable_telegram` [True/False] and `enable_discord` [True/False] which I think are pretty self-explainatory ;)

**Comment by bonny1992** [comment]
I'll reopen the issue if there will be more problem with this.
